version: "2.1"

services:
  localstack:
    image: public.ecr.aws/localstack/localstack:4.14
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
