name: CI
on: [push]

env:
  DEBIAN_FRONTEND: noninteractive
  AWS_ENDPOINT: http://localhost:4566

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sqs
          DEFAULT_REGION: us-east-1
        ports:
          - 4566:4566
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Wait for Localstack SQS to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:4566/_localstack/health >/dev/null; then
              echo "Localstack is healthy"; break; fi; sleep 2; done

      - name: Run unit tests (no integration tag)
        run: go test ./...

      - name: Run producer integration tests
        run: go test -tags=integration ./...
