name: CI
on: [push]

env:
  DEBIAN_FRONTEND: noninteractive
  AWS_ENDPOINT: http://localstack:4566

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.21.6-alpine3.19
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: sqs
          DEFAULT_REGION: us-east-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: apk add git gcc musl-dev
      - run: go test ./...
  snyk-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: snyk/actions/setup@master
      - run: snyk test
